name = "aura-checkout"
main = "checkout.js"
compatibility_date = "2024-01-01"

# Custom domain for API
routes = [
  { pattern = "api.new-vansky.com", custom_domain = true }
]

# Environment variables (DO NOT commit secrets here)
# Set these in Cloudflare Dashboard or use wrangler secret
# STRIPE_SECRET_KEY = "sk_live_..." # Set via: wrangler secret put STRIPE_SECRET_KEY
